### ISSUE TITLE
[Release-1.0] Setup proper error logging

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/gruveebackend#34]
We should find a cool error logging system that could with firebase and our functions

**Comment by adilanchian** [comment]
https://cloud.google.com/error-reporting/docs/reference/libraries

**Comment by adilanchian** [comment]
@LeviHarrison - 

So given the hype around Sawmill today, would you be open in collabing on an independent Golang logging package? If anything we can just keep it in our current repo? haha

**Comment by LeviHarrison** [comment]
Sure! I'm not really certain how much I can add to any Golang project with my meager skills in the language, but I think it would be really fun to give it a try.

**Comment by adilanchian** [comment]
@all-contributors please add @LeviHarrison for code

**Comment by adilanchian** [comment]
Legit can't believe this is done haha. Thanks for all the hard work! CONGRATS!!!
