### ISSUE TITLE
🛠 Developer tools: Update VS Code go lang extension publisher ID

### ISSUE THREAD

**Issue by edburtnieks-archive** [PixelogicDev/gruveebackend#37]
Upon [VS Code Go extension joining the Go project](https://blog.golang.org/vscode-go) the publisher ID has changed from `ms-vscode.go` to `golang.Go`

**Comment by adilanchian** [comment]
Holy cow. Thank you for this!!! Been meaning to get this done haha

**Comment by adilanchian** [comment]
@isabellabrookes do you think you'd be able to setup the contribution bot for this repo as well?

**Comment by isabellabrookes** [comment]
@adilanchian did you accept the bot?

**Comment by adilanchian** [comment]
@isabellabrookes hey! I did accept it the other day so I think we should be good.... so it will essentially pick up all the contributors for us right? We don’t have to manually worry about it?

**Comment by isabellabrookes** [comment]
@all-contributors please add @edburtnieks  for code
