### ISSUE TITLE
[Release-1.0] Setup Apple Auth

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/gruveebackend#4]
This should be done through Firebase as they have a setup for this can more instructions can be found here:

https://firebase.google.com/docs/auth/web/apple

**Comment by adilanchian** [comment]
We need to create a test Apple account to sign into and such

**Comment by adilanchian** [comment]
NOTES:

I created a new Apple ID and things seemed to work fairly well, until we kept receiving error 1000 in simulator. I think the next test is to test on my device. If it works on my device, then its a simulator else I need to go through the Apple Auth Setup again.

**Comment by isabellabrookes** [comment]
@all-contributors please add @adilanchian  for code, maintenance, docs

**Comment by adilanchian** [comment]
Checked in and deployed to master :)
